// <auto-generated />
using System;
using ApiGestion.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiGestion.Migrations
{
    [DbContext(typeof(ClinicaContext))]
    partial class ClinicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiGestion.Models.Apliacion", b =>
                {
                    b.Property<int>("Idaplicacionvacuna")
                        .HasColumnType("int")
                        .HasColumnName("IDaplicacionvacuna");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("Idmascotas")
                        .HasColumnType("int")
                        .HasColumnName("IDmascotas");

                    b.Property<int>("Idtipovacuna")
                        .HasColumnType("int")
                        .HasColumnName("IDtipovacuna");

                    b.Property<int>("Idvacuna")
                        .HasColumnType("int")
                        .HasColumnName("IDvacuna");

                    b.Property<int>("Idveterinario")
                        .HasColumnType("int")
                        .HasColumnName("IDveterinario");

                    b.HasKey("Idaplicacionvacuna");

                    b.ToTable("Apliacion", (string)null);
                });

            modelBuilder.Entity("ApiGestion.Models.Consulta", b =>
                {
                    b.Property<int>("Idconsultas")
                        .HasColumnType("int")
                        .HasColumnName("IDconsultas");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime");

                    b.Property<int>("Idmascota")
                        .HasColumnType("int")
                        .HasColumnName("IDmascota");

                    b.Property<int>("Idveterinario")
                        .HasColumnType("int")
                        .HasColumnName("IDveterinario");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Idconsultas");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("ApiGestion.Models.Dueño", b =>
                {
                    b.Property<int>("Iddueño")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Iddueño");

                    b.ToTable("Dueño", (string)null);

                    b.HasData(
                        new
                        {
                            Iddueño = 1,
                            Direccion = "Calle Falsa 123",
                            Dni = 12312354,
                            Email = "juansito@gmail.com",
                            Nombre = "Juansito",
                            Telefono = 1153432132
                        },
                        new
                        {
                            Iddueño = 2,
                            Direccion = "Av. Siempre Viva 742",
                            Dni = 30111222,
                            Email = "maria.lopez@gmail.com",
                            Nombre = "María López",
                            Telefono = 1145678901
                        },
                        new
                        {
                            Iddueño = 3,
                            Direccion = "San Martín 500",
                            Dni = 28999888,
                            Email = "carlos.perez@gmail.com",
                            Nombre = "Carlos Pérez",
                            Telefono = 1133345566
                        },
                        new
                        {
                            Iddueño = 4,
                            Direccion = "Belgrano 250",
                            Dni = 27888777,
                            Email = "ana.torres@gmail.com",
                            Nombre = "Ana Torres",
                            Telefono = 1122233344
                        },
                        new
                        {
                            Iddueño = 5,
                            Direccion = "Mitre 100",
                            Dni = 26777666,
                            Email = "luis.fernandez@gmail.com",
                            Nombre = "Luis Fernández",
                            Telefono = 1199988877
                        },
                        new
                        {
                            Iddueño = 6,
                            Direccion = "Rivadavia 321",
                            Dni = 25666555,
                            Email = "sofia.ramirez@gmail.com",
                            Nombre = "Sofía Ramírez",
                            Telefono = 1188877766
                        },
                        new
                        {
                            Iddueño = 7,
                            Direccion = "Colón 50",
                            Dni = 24555444,
                            Email = "martin.gonzalez@gmail.com",
                            Nombre = "Martín González",
                            Telefono = 1177766655
                        },
                        new
                        {
                            Iddueño = 8,
                            Direccion = "Independencia 88",
                            Dni = 23444333,
                            Email = "laura.diaz@gmail.com",
                            Nombre = "Laura Díaz",
                            Telefono = 1166655544
                        },
                        new
                        {
                            Iddueño = 9,
                            Direccion = "Italia 12",
                            Dni = 22333222,
                            Email = "pedro.sanchez@gmail.com",
                            Nombre = "Pedro Sánchez",
                            Telefono = 1155544433
                        },
                        new
                        {
                            Iddueño = 10,
                            Direccion = "España 77",
                            Dni = 21222111,
                            Email = "valentina.herrera@gmail.com",
                            Nombre = "Valentina Herrera",
                            Telefono = 1144433322
                        });
                });

            modelBuilder.Entity("ApiGestion.Models.Especialidad", b =>
                {
                    b.Property<int>("Idespecialidad")
                        .HasColumnType("int")
                        .HasColumnName("IDespecialidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Idespecialidad");

                    b.ToTable("Especialidad", (string)null);
                });

            modelBuilder.Entity("ApiGestion.Models.Especie", b =>
                {
                    b.Property<int>("IdEspecie")
                        .HasColumnType("int")
                        .HasColumnName("idESPECIE");

                    b.Property<bool>("Gato")
                        .HasColumnType("bit")
                        .HasColumnName("gato");

                    b.Property<int>("Idmascota")
                        .HasColumnType("int")
                        .HasColumnName("IDmascota");

                    b.Property<bool>("Loro")
                        .HasColumnType("bit")
                        .HasColumnName("loro");

                    b.Property<bool>("Perro")
                        .HasColumnType("bit");

                    b.HasKey("IdEspecie");

                    b.ToTable("Especie", (string)null);
                });

            modelBuilder.Entity("ApiGestion.Models.Foto", b =>
                {
                    b.Property<int>("Idfoto")
                        .HasColumnType("int")
                        .HasColumnName("IDfoto");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("Idmascota")
                        .HasColumnType("int")
                        .HasColumnName("IDmascota");

                    b.Property<byte[]>("Imagen")
                        .IsRequired()
                        .HasColumnType("image")
                        .HasColumnName("imagen");

                    b.HasKey("Idfoto");

                    b.ToTable("fotos", (string)null);
                });

            modelBuilder.Entity("ApiGestion.Models.Mascotum", b =>
                {
                    b.Property<int>("Idmascota")
                        .HasColumnType("int")
                        .HasColumnName("IDmascota");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Iddueño")
                        .HasColumnType("int")
                        .HasColumnName("IDdueño");

                    b.Property<int?>("Idraza")
                        .HasColumnType("int")
                        .HasColumnName("IDraza");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Raza")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Señas")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Idmascota");

                    b.ToTable("Mascota");
                });

            modelBuilder.Entity("ApiGestion.Models.Medicamento", b =>
                {
                    b.Property<int>("Idmedicamento")
                        .HasColumnType("int")
                        .HasColumnName("IDmedicamento");

                    b.Property<string>("Droga")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("droga");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Presentacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Idmedicamento");

                    b.ToTable("Medicamento", (string)null);
                });

            modelBuilder.Entity("ApiGestion.Models.Raza", b =>
                {
                    b.Property<int>("Idraza")
                        .HasColumnType("int")
                        .HasColumnName("IDraza");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Taamaño")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Idraza");

                    b.ToTable("RAZA", (string)null);
                });

            modelBuilder.Entity("ApiGestion.Models.Tipovacuna", b =>
                {
                    b.Property<int>("Idtipovacuna")
                        .HasColumnType("int")
                        .HasColumnName("IDtipovacuna");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Idtipovacuna");

                    b.ToTable("tipovacuna", (string)null);
                });

            modelBuilder.Entity("ApiGestion.Models.Tratamiento", b =>
                {
                    b.Property<string>("Idtratamiento")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("IDtratamiento")
                        .IsFixedLength();

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dosis");

                    b.Property<int>("Duracoin")
                        .HasColumnType("int")
                        .HasColumnName("duracoin");

                    b.Property<int>("Idconsultas")
                        .HasColumnType("int")
                        .HasColumnName("IDconsultas");

                    b.Property<string>("Idmedicamento")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("IDmedicamento")
                        .IsFixedLength();

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Idtratamiento");

                    b.ToTable("TRATAMIENTO", (string)null);
                });

            modelBuilder.Entity("ApiGestion.Models.Veterinario", b =>
                {
                    b.Property<int>("Idveterinario")
                        .HasColumnType("int")
                        .HasColumnName("IDveterinario");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Idespecialidad")
                        .HasColumnType("int")
                        .HasColumnName("IDespecialidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Nummatricula")
                        .HasColumnType("int");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Idveterinario");

                    b.ToTable("veterinario", (string)null);
                });

            modelBuilder.Entity("ApiGestion.Models.Veterinarioespecialidad", b =>
                {
                    b.Property<int>("Idveterinarioespecialidad")
                        .HasColumnType("int")
                        .HasColumnName("IDveterinarioespecialidad");

                    b.Property<int>("Idveterinario")
                        .HasColumnType("int")
                        .HasColumnName("IDveterinario");

                    b.HasKey("Idveterinarioespecialidad");

                    b.ToTable("VETERINARIOespecialidad", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
